### ISSUE TITLE
Select Character Crash

### ISSUE THREAD

**Issue by Azakren** [Icydeath/HealbotConfigurator#4]
Exact Issue:
- Dropdown on select character causes crash when picking any character.
![Image2](https://user-images.githubusercontent.com/16009257/126729335-b3902d38-b3b8-4f22-b7dd-aaa05d021bfe.jpg)

Healbot Configurator Versions:
- 1.0
- 1.1
- 1.2

Troubleshooting tested:
- Downloaded new EliteMMO.API.dll and EliteAPI.dll and replaced them on all versions.
- Unblocked zip release before extracting on all versions.
- Ran as admin on all versions.
- Ran in Windows 7 compatibility mode on all versions.
- Made sure lor libs correctly installed in C:\Program Files (x86)\Windower\addons\libs\lor
- Made sure the actual Healbot plugin was loaded and working.

**Comment by Icydeath** [comment]
I'm sorry to hear you are having issues. I'm working on a redesign of the tool that should resolve a lot of the crashing issues. If I identify the issue specific to these versions I will report back here.

**Comment by Kiza143** [comment]
The crash is caused from the Windower4 path. if you don't have it in the x86 folder you just need to change the path eg C:\Users\User\Desktop\Windower is mine

**Comment by Icydeath** [comment]
Good catch @Kiza143 

 @Azakren when you change your windower path in the tool does it still error out?

**Comment by Azakren** [comment]
I moved my windower folder to :
C:\Users\Administrator\Desktop\Windower
and that fixed the issue, thanks~

**Comment by Icydeath** [comment]
Great to hear!
