### ISSUE TITLE
Crashes when selecting character.

### ISSUE THREAD

**Issue by Billbo1** [Icydeath/HealbotConfigurator#5]
Just switched over to HB from using Cureplease, the config UI opens up just fine, but when i select a character it instantly crashes with no warning, ive made sure to update Api etc, not sure how to get it to work really, running as admin etc etc, Thanks

**Comment by Icydeath** [comment]
Which version are you using. If its the latest version (1.3) some people are having issues with it, try the 1.2 version and see if you still have the issue.

**Comment by rckpullins** [comment]
At the top of the program, make sure you set your windower path.
