### ISSUE TITLE
Erase isn't working

### ISSUE THREAD

**Issue by budstar** [Icydeath/HealbotConfigurator#6]
I don't know if it's just me or anyone else is having this problem but my whm doesn't use erase for example for slow even if it's enabled.

**Comment by Icydeath** [comment]
Just noting that removing debuffs (via erase an other spells) is controlled via the priorites.lua > 'status_removal' section.
![image](https://user-images.githubusercontent.com/6233937/151996075-f0eca6b0-9f92-416b-b62c-20f6d8a32342.png)
