### ISSUE TITLE
November 2021 version update

### ISSUE THREAD

**Issue by undiebear** [Icydeath/HealbotConfigurator#7]
Hi, after the version update today the configurator doesnt appear to be working anymore. You can run the program just fine but when you press on after loading the profile you want nothing happens...been working fine uptil now though :)
today after checking again when you try to load your profile however it just crashes out.

**Comment by Icydeath** [comment]
You may need to update the elitemmo dll's. I haven't logged on in a bit but I'm guessing that's the issue.

**Comment by undiebear** [comment]
yeah looking at their site, appears its been updated now.
