### ISSUE TITLE
Is this healbotconfigurator still working?

### ISSUE THREAD

**Issue by comola** [Icydeath/HealbotConfigurator#8]
Hi there,
I try download and unzip the file. Than downloaded the latest EliteAPI.dll and EliteMMO.API.dll. When I click run as administrator on the program nothing happen. Is like the software did not load at all.

Am I missing a step?

**Comment by Icydeath** [comment]
Yes it should still be working but v1.3 has issues.
Try version 1.2: https://github.com/Icydeath/HealbotConfigurator/releases/tag/v1.2

**Comment by Icydeath** [comment]
Any luck?
